# Generated by Django 3.2.4 on 2021-06-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
        migrations.AlterField(
            model_name='variation',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date ajout'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='est-active'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100, verbose_name='Couleur ou taille'),
        ),
        migrations.AlterField(
            model_name='variation',
            name='variation_value',
            field=models.CharField(max_length=100, verbose_name='Valeur'),
        ),
    ]
